parameters:
    ab_oauth2_facebook_grant.grants.facebook.class: AdrienBrault\OAuth2FacebookGrantBundle\OAuth2\FacebookGrantExtension

services:
    ab_oauth2_facebook_grant.grants.facebook:
        class: %ab_oauth2_facebook_grant.grants.facebook.class%
        arguments:
            - null # userProvider
            - @ab_facebook_client.client
